language: ruby
rvm:
- 1.9.3
- 2.0.0
- 1.9.2
- ruby-head

env:
- "CHEF_VERSION=11.8.0"
- "CHEF_VERSION=11.4.0"
- "CHEF_VERSION=10.24.0"
- "CHEF_VERSION=0.10.10"

matrix:
  allow_failures:
  - rvm: ruby-head
